### ISSUE TITLE
Compiler macro for `#'vect` causes problems for vectors of lists

### ISSUE THREAD

**Issue by djeis97** [TBRSS/serapeum#14]
`(vect (list 'foo))` breaks in compiled code on SBCL because the compiler-macro declares `(list 'foo)`dynamic-extent at the same time as it declares the temporary list for passing to make-array dynamic-extent.

This is a very particular edge case, and one that can be easily solved by users without any change to vect, but it is very surprising when you're not expecting it. At the very least, a note in the docs would be appreciated.

As a side note, this is reproducible at the repl by wrapping the example above in a lambda, as in `((lambda () (vect (list 'foo))))`. The result is a vector containing junk data.

**Comment by ruricolist** [comment]
It's kind of you to call it an edge case, but no, it's definitely a bug.

I'll fix it ASAP, but that might not be till Monday, so if it's urgent I'd be happy to merge a pull request that removes the offending dynamic-extent declaration.
