### ISSUE TITLE
some naming-conventions

### ISSUE THREAD

**Issue by cl-porky11** [TBRSS/serapeum#8]
predicate-functions with `-` inside normally have also a `-` before the `p`
so `string-containsp` should be `string-contains-p` and `string-tokenp` should be `string-token-p`

**Comment by ruricolist** [comment]
I was trying to be consistent with other `string-` predicates in CL: `string-greaterp`, `string-lessp`. But if it's confusing maybe I should reconsider.

**Comment by PuercoPop** [comment]
Fwliw, I think it is better to follow the rule @cl-porky11 mentions. No need to increment the list of exceptions to the rule for the p/-p archaism.
