### ISSUE TITLE
MAP-TREE behavior

### ISSUE THREAD

**Issue by fiddlerwoaroof** [TBRSS/serapeum#9]
Does the implementation of MAP-TREE match the documentation?  The docstring specifies that you throw TAG in order to skip the current subtree, but at <https://github.com/TBRSS/serapeum/blob/master/trees.lisp#L58> it looks like throwing TAG aborts walking completely and returns the thrown value instead of continuing through the tree.

**Comment by ruricolist** [comment]
As it turns out, it didn't match, because the definition was wrong.
